apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:SRh3S9vImB9+xCvW3yy1tEDyLZzQCT4=,iv:EVTyCSWgAE3cK7iAo/ll4U/WDvV4mYMtFUWCxXSlUzI=,tag:Gr/FejHXRS2ZFjMrgHSCcw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFFHV2tjUGla
        OHpzYVoxeXdpSkhyNFJ6QVB6RDM4ZmFpMmgwU3hmNDBySmlhKzEzelhiUWVuUjFa
        LzQ1bmdMcnFIS1JsOGF3MS8vMUFTWHpOTEUzcUJRK1k0eW1wWU5zMTBISVRiVE9U
        ZnBPNFkvMEVjNWVidEVjUHN2bzE1NW5SMXFEcjk0TU1zQ0VKeS93STlVZVJBVGFp
        Ym5FVnhvNjNHMXhxbVpVTzJjZ0JkMnpvTUNDaGxZRmJvQjFTOE42eEtjTFZHZlEx
        ZG5CaFh6L2JlQlp5cGYyaGRqUDRvU1dtZDZiUlZmOWc5M3d6NGZzR0FjZW9DQkp3
        Q1JRRG9YNmhWNTJQbDFxWnE3Yyt3Q0hLTzEzeUJ1SjRqZ0duQ1NGZGEzbnZSaWp6
        MkpFYnRnODlwdWFlT1RwTDNtQk40Q1Q0L2lMM2wwcFVrS3FDaWhyZ2ZhQVdBM2V0
        YzdkUmxYOGxaK3FESFc4ZHgyRnhIVVNYL0VuV3NYQnpsR3hGMHdIYmVzR3UrbkEz
        czBLWWpMVXZkOE5xdmFmYWhDVEdiMXJpWjFTZXdSd3hYaXcxZTBtWmxHZ3lQZThR
        c01KWVdpU3V6YjN6ZGZGS0J0eTBFeHZqaTRaZmJDNVlIT00xQm10dFhTN3FSdjVQ
        aXNRbGNmQW5mU1VNV1doaE50bCtSUVJFUURncElEc2hYOGpZM3MrbEcyV3lYSVhp
        RnJQQTltZXJ6ZDI2R1dMR1YxODQ0bWI4UWd3Znl4QlNLcnRiVktJdFFYaVpTLzQr
        YmZwSWYvbjZVdytteXppRUs1RHlSNStRNjR4eXFFd0xGcTRCSlpid1QxMm1FckZw
        Ty9udDdJY2tzWm51R1BEbWZGTncvZ2w3eXZtdDI0QitlVVRuQ2hoNFhZa251UGJ1
        ZGNnSFBpNHdJL01qd2RKV2FEaHhHaFRrYTdONFo1SWdOanhUM0Y0KzF2TktnNWZ0
        ay9jY25VUnllcUIreVBoOHBXdXdjTkMrQW9TNjBsUVloZFBWZFRRSDRoVkplbkhZ
        WHpOWHg5ZFVJRWlRNEIyQy9RWlZaclp0bGplelR3UjlqSi9rclJFRlZwaThLRFNX
        cVhTNmpDSWEybUpZSGpObXdFSG95ZDRDS3RxZDQ3V095MWo1cC9Da3NHOFM2V2NY
        Mnd0Y1VkTW1aVkgyVCtiY3FSTkx1SllISk9CMG1ib1FRcGRkRWp0SlZxZmRrVXFl
        clpaVTVjTjRiQUxyekRVd1hWdHVvQjJac0t1S0FpeUN2b3A4WmpEeW0xN0FOSytF
        L2F4ZERobVlsUGtleGt4QXlneWtiV1dhVlBYV2x3MGJhU1VFQTVKWWJxMHlJUVJU
        YVZ0cFd0MVJpcVlpcjlPd2l4bnlGNXUzbmdrcis2NnJOdnlTZjNkSU90WndRKzIv
        M2ZnajFOcHpveGc2Z0NXR2NrUGs3OGRkMjI5V3d1cWVrTTZ5MmxoMWlVVmJQYjA2
        bEVra09GOHQ4VlltMVdHU290aHhLT3ZYUStMY21IdnlyYXBpWFlwa2ZtUnlrRWYz
        VUNRbVh1OWoxbXR3REp3dEh3Nm1CcmJPYm1xZFdDdDU2dWE4a1NRV0I1Zmtnc0x6
        M2hBaHhNYWVUTjNoYVVZT2hGSnlkcnl0RXZvN2djR1FadXZtdHpNK1VMYVlJL3NS
        Vjhucm90czNNTk9Sa0xDZEpsTmZqMUJ1UWdTUTBFMHlxZmoxMUtad3NQSUpCOC85
        bVJ5WkNybFZ5QWg2alF1TC8xQ1NQSWFWNTJhaUJIaGxPRUlraHR4SUU5aVVJRG52
        TCs1dmRkWGM0OFhhVkhQZnhKRkhJMVgvTVFESWxyc0ZmK3N4aWd5Y1EybmQwd2VK
        emM5dThZNDFHT01ReXNnUWVBVm9kZWZPNDNlN3BpMTAxNzVBaUlZdXIxZklyNVVK
        QU00UFE5RytpM0xqbSs4KytNbCtIV084WnVvZVlRdTRvSStMblpZY0lzWldUdwpH
        RER5UEtGRllTNmVnMkFwb3R0S1NuYlVuYUROcUFjQTR6N2pZaDdGSkZzCi0tLSBK
        R3lvTGNCMk9FeHVIZmlzR0lYUEd0aTJpRzdOWVdBUU41RGs3NjZ6QWlNCml3bm+O
        oZ4dR9dI1jXVviqtwXAoLlf5tk2qFQOLIWMhuQBZdn737XTU2kkSj+Tapkb0ct3a
        DWfpuxtHV9o19JI=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq19gpgm3auqc0u09c0nsw06gdvrz2efx9ygq94hnd0x4ckfz4a4e9xa6vcy9p0y353tzgymz9twspv0fzjgjayxn7yvstsn929pk4cmflfsls7y6wl3yaetceq0nu3v5xxvqe7dwcn4pe27a24cm4vfafjp6vujc6f7zgzgmrdktykt06zpdq3xqsy0yzuxw9fnfjzx5vjwe98c3nak6fdm2kzdzwpdra5y9mfhrpjk4fmny55792zxq0qh3qzqwxg00yg0yzkx0ceqv3v3j9hjgeqc3e2qp7zfu989h0npzm5qma9qxxx3a4cfdzykkf9sfzcvw7zt2jhmummw5y5qd89sga0q57agrrexwgj3qrp77jz8vvjwtnztsfk4vjyv0rynr3kdnn0jphhcgrzf5qm6w7xxelk3tmm26y7ggxuzz4llmk8cq79h54zvt30d232z62czxpxsaqxcd9f9y2x7ss8we925a4rqdlfcfn68p3q4y99evvqmnxgc8lucv40gdw6spuka6jye2w83vaqvljayzx8fw46gaet54xqfwkmy5jjq6dn6y027zeslezxvwctkathqnsujy7hg9wfdxxzl8ccs0fkf8x5dz9j0efeuksgrghe0xwtsf6mghyvsq2pvwg47tt8kw0jgr200fe5jx6t2usgd8rej0ysf3xt5qel49eknjftgp0v3vw3pd06kd4s0v4mt4sp77v90tchkrtgvxyvdv5g0tdt6qrk5etnhsqx0wd6yzgrg3cp7mzxjmlppwjaq6tx672ykzzqdydhcd455xmakxl9rva826nfc0ws2tr53y3thgd7taq48lanwmzj34rypqlkdn8mg6q7u0yqglyqsxlvr3j7af3hw5eegaahjk64d6q3c9ujffrprg3mpmje2w2scfe2j3c7kzjhcxqsy66yepk9w5xqzdht5lqxmuxzr2wy8qqjhcwctvgaqsvsu7qvujfcc9zjpf7wszdaf3ryk2jj66e874rcwjttwma466dmajqzjfu6ll09g786z963lv44wfcnjgk9zrcstzrhc7e7uw0eserghsu5d7h8r44ejurr5syfrgf2sr7p63wmetph58ydczj9jx50ckveucxmcdtxzasjjp00a9wwfputkcg9t0wp9fzl0xmcd43qqcfz8t76fxcu4ytl8dnvl9ffn2gp56y3qu94kmcvfgy6fqs9u5j9lqm8g667h0ahx9ahkde7hxamc75535fq8jep6x3kjktl0krj8v93e026xfye32hlfdqqg8s6ekjtcf72zle40zrc2g9f8vunu6c8w4mz0vg6lyg203a2l8ckywtp2y3cvfrs229jm3ygyzdejw9ev6yjns5u2u7nuhqxa29fjwsx0lrn9gg4js3lkqdlewged2n5xqqttrsx3s5eg7r0t0g4y50jtdt73r3lrgp42w7zgcqfvgy8f367ka7hhqdsvu5vlp39vdcfc4hmy95j254u57vqznmzg7l3pazzzk436csmzesedtae7w7zvj7leyk4tw38wje084ah56mgv82updysu7zj3gzn7frt0evszezdvkwke8z85kdkx2e4nqhmguj0hr94u2caujrngd3eqknsdp8hqyy4qegjzfg2qct8xw83x2dpfr65qcgkvdt7fdccypxsh0m0q4u0jxecdc4krdqscyesyu2nkvt3rfjfwq5ezg2cpztupr85w0vatgwmz9sgnp360vzjhw6xe9rphjs8vgsnn36q0fsu3vxsyp9gtdnzpdcfvtzesjez48pyw2l52wf4hz6m9p9c8j58p7k0wqda7hremk2v78ut66wmg5gdee3nvm3appaa5fex2vvs5k0rcr8hsaw2r8gq77jyr5cpxq8pgc9gjwdfwsy9j4qzxsf6dyz94pxsytu4gzk62yk7ap2r
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-03T05:45:06Z"
  mac: ENC[AES256_GCM,data:db87O0A/4cq3DEVSyuGo6vtdwsRxWtHIyt0tenqijj4Lh/I3nFNBRSYLGFn5jaPkqugWNZ3/z0Ce64R2Vto08fvWJIGeUajCBiBCieAf8WvuCXhA9FIFFWkp7pMmpOX5tU+2CSioOhB26JY5Z16/63Qkdg203YCIbzTcgOnLoRg=,iv:gaq0J0C0Kb5MPbUX/CfXqucKzEigjoxIp8Xnhat0wqo=,tag:1ZYvA8Byi7a4teokWL+VIg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
