# values.yaml
replicaCount: 1

image:
  pullPolicy: IfNotPresent

persistence:
  config:
    enabled: true
    size: 50Gi
    storageClass: "longhorn"
    replicaCount: 1
  media:
    enabled: true
    size: 500Gi
    existingClaim: nfs-media-pvc

image:
  pullPolicy: IfNotPresent

httpRoute:
  enabled: true
  annotations: {}
  parentRefs:
    - name: envoy-internal
      namespace: network
  hostnames:
    - amusement-zone.house
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: jellyfin
          port: 8096

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi

nodeSelector: {}
tolerations: []
affinity: {}
